---
- name: Check for existing SSH communication with Github
  command: ssh -T git@github.com -o StrictHostKeyChecking=no
  register: has_github_ssh
  ignore_errors: true

- name: Add your key to Github (with 2FA)
  when: has_github_ssh | failed
  command: http -b --auth {{ github_user_name }}:{{ github_auth_token }} POST https://api.github.com/user/keys title="{{ computername }}" key="`cat ~/.ssh/id_rsa.pub`"