---
- hosts: localhost
  connection: local

  ### Not here yet: 
  # - Act On Mail
  # - MS Office enterprise
  # Safari extensions
  # abby scan thing sprint
  #

  vars:
    - superlimic_config_repo: https://github.com/franklouwers/superlumic-config.git
    - user_name: frank
    - computername: tembo
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: frank@louwers.be
    - github_user_name: franklouwers
    - git_user_name: Frank Louwers
    - git_user_email: "{{ user_email }}"
    - git_signing_key: EF7394AA445AECCC
    - apple_id_email: frank@tembo.be
    - src_dir: "{{ home_dir }}/src/"
    - settings_export_dir: "{{ home_dir }}/tmp/SettingsExports"
    # Set these in secrets file:
    # github_auth_token
    # apple_id_password

  vars_files:
    - vars/osx_defaults.yml
  #    - vars/sublime_text_packages.yml
    - vars/{{ user_name }}-secrets.yml

  roles:
    - { role: profile-all, tags: base }
    - { role: profile-developer, tags: base-dev }
  #  - { role: sublimetext3, tags: sublime }
    - { role: ruby, tags: ruby }
    - { role: zsh, tags: zsh }
    - { role: frank-terminal, tags: terminal }
    - { role: vim, tags: vim }

  tasks:
    - name: homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/cask-eid
        - homebrew/cask-drivers
        - homebrew/cask-fonts
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - keepingyouawake
        - calibre
        - charles
        - chefdk
        - vagrant
        - docker
        - google-chrome
        - firefox
        - handbrake
        - spotify
        - tripmode
        - whatsapp
        - tunnelblick
        - hosts
        - alfred
        - adguard
        - virtualbox
        - typora
        - carbon-copy-cloner
        - eid-be
        - keybase
        - java
        - libreoffice
        - real-vnc
        - virtualbox
        - hazel
        - adobe-acrobat-reader
        - docker
        - telegram
        - grammarly
        - gpg-suite
        - backblaze
        - mactex
        - rocket-chat # open-xchange chat tool


    - name: Create local bin dir
      file: path="{{ home_dir }}/bin" state=directory

    - name: Copy local 'binaries'
      copy: src=files/frank/bin/
            dest="{{ home_dir }}/bin/"


    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - node
        - mas
        - certbot
        - z
        - ipcalc
        - jq
        - mtr
        - unrar
        - csshx
        - colordiff
        - macvim
        - grep
        - recode
        - nmap
        - telnet
        - p7zip
        - go
        - python
        - python@2
        - sphinx-doc
        - trash

    - name: "[App Store] Sign out of the Mac App Store"
      command: mas signout

    - name: "[App Store] Sign in to the Mac App Store"
      command: mas signin {{ apple_id_email }} "{{ apple_id_password }}"

    - name: "[App Store] See which apps are already installed"
      command: bash -c "mas list | cut -f 1 -d ' '"
      register: mas_list


# mas broken in Mojave :(
# Update: mas fixed for Mojave! (1.4.3)

    - name: "[App Store] Install Mac App Store applications"
      command: mas install {{ item.id }}
      when: item.id not in mas_list.stdout_lines
      with_items:
        - { id: "1333542190", name: "1Password 7" }
        - { id: "409183694", name: "Keynote" }
        - { id: "540348655", name: "Monosnap" }
        - { id: "1295203466", name: "Microsoft Remote Desktop 10"}
        - { id: "1327661892", name: "XMind ZEN" }
        - { id: "1063996724", name: "Tyme2" }
        - { id: "1384080005", name: "Tweetbot" }
        - { id: "803453959", name: "Slack" }
        - { id: "409201541", name: "Pages" }
        - { id: "407963104", name: "Pixelmator" }
        - { id: "1170434079", name: "ScanSnap Cloud" }
        - { id: "409203825", name: "Numbers" }
        - { id: "460866217", name: "Simple Desktops" }
        - { id: "944960179", name: "Any.do" }


    - name: create .ssh directory
      file:
        path: "{{ home_dir }}/.ssh/"
        state: directory
        mode: 0700

    - name: personal ssh config
      copy:
        src: files/ssh_config
        dest: "{{ home_dir }}/.ssh/ssh_config"
