---

- hosts: 127.0.0.1
  connection: local

  vars:
    - user_name: joff
    - computername: cernan
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: joff@joff.codes
    - github_user_name: joffotron
    - git_user_name: Joseph Miller
    - git_user_email: "{{ user_email }}"
    - git_signing_key: 198C913B

  vars_files:
    - vars/osx_defaults.yml
    - vars/sublime_text_3.yml
    - vars/{{ user_name }}-secrets.yml

  roles:
    - profile-all
    - profile-developer
    - roderik.superlumic-sublimetext
    - ruby
    - python
    - profile-caremonkey-dev
#    - other-languages

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - istat-menus
        - dropbox
        - kaleidoscope
        - xee
        - bartender
        - chicken
        - alfred
        - bettertouchtool
        - tresorit
        - evernote
        - skitch
        - gitkraken
        - monodraw
        - moom
        - flux
        - datagrip
        - intellij-idea
        - rubymine
        - sonos
        - spotify
        - libreoffice

#        Missing AppStore apps: Wunderlist, LSwitch, WSwitch, Affinity Photo+Designer, Sunrise, 3Hub,
#                               Tweetbot, Docker Beta

    - name: Local bin dir
      file: path="{{ home_dir }}/bin" state=directory

    - name: Powerline Shell Prompt
      git: repo=https://github.com/milkbikis/powerline-shell
           dest="{{ home_dir }}/bin/powerline-shell"
           version="master"

    - name: Run install for powerline shell prompt
      command: "python install.py"
      args:
        chdir: "{{ home_dir }}/bin/powerline-shell/"

    - name: homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/fuse
        - Caskroom/cask

    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - certbot
        - z
        - ipcalc
        - jq
        - moreutils
#        - osxfuse
#        - ntfs-3g
        - packer
        - pidof
        - s3cmd

    - name: create .ssh directory
      file:
        path: "{{ home_dir }}/.ssh/"
        state: directory
        mode: 0700

    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: "{{ home_dir }}/.ssh/ssh_config"

    - name: Copy Jetbrains Settings Files
      copy: src="{{ user_name }}/{{ item }}-settings.jar" dest="{{ home_dir }}/Desktop/{{ item }}-settings.jar"
      with_items:
        - RubyMine
        - IntelliJ
        - DataGrip

    - name: Install Python pip packages
      pip: state=present name="{{ item }}"
      with_items:
        - awslogs
        - wharfee

