---

- hosts: 127.0.0.1
  connection: local

  vars:
    - user_name: joff
    - computername: cernan
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: joff@joff.codes
    - github_user_name: joffotron
    - git_user_name: Joseph Miller
    - git_user_email: "{{ user_email }}"
    - git_signing_key: 198C913B

  roles:
    - profile-all
    - profile-developer
    - ruby
    - python
    - sublime_text_3
#    - other-languages

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - istat-menus
        - dropbox
        - kaleidoscope
        - xee
        - bartender
        - chicken
        - alfred
        - bettertouchtool
        - tresorit
        - evernote
        - skitch
        - gitkraken
        - monodraw
        - moom
        - flux
        - datagrip
        - intellij-idea
        - rubymine
        - sonos
        - spotify
        - libreoffice

#        Missing AppStore apps: Wunderlist, LSwitch, WSwitch, Affinity Photo+Designer, Sunrise, 3Hub,
#                               Tweetbot, Docker Beta

    - name: Local bin dir
      file: path="{{ home_dir }}/bin" state=directory

    - name: Powerline Shell Prompt
      git: repo=https://github.com/milkbikis/powerline-shell
           dest="{{ home_dir }}/bin/powerline-shell"
           version="master"

    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - certbot
        - z
        - ipcalc
        - jq
        - moreutils
        - ntfs-3g
        - packer
        - pidof
        - s3cmd
        - spread

    - name: create .ssh directory
      file:
        path: "{{ home_dir }}/.ssh/"
        state: directory
        mode: 0700

    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: "{{ home_dir }}/.ssh/ssh_config"

    - name: Copy Jetbrains Settings Files
      copy: src="{{ user_name }}/{{ item }}-settings.jar" dest="{{ home_dir }}/Desktop/{{ item }}-settings.jar"
      with_items:
        - RubyMine
        - IntelliJ
        - DataGrip

    - name: Install Python pip packages
      pip: state=present name="{{ item }}"
      with_items:
        - awslogs
        - wharfee

    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: 'Clicking'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'com.apple.mouse.tapBehavior'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'ApplePressAndHoldEnabled'
        type: boolean
        value: false
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'NSGlobalDomain'
        key: 'AppleShowScrollBars'
        type: string
        value: always
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode2'
        type: boolean
        value: true

#      - domain: 'com.apple.dock'
#        key: 'minimize-to-application'
#        type: integer
#        value: 1
#      - domain: 'NSGlobalDomain'
#        key: 'NSTableViewDefaultSizeMode'
#        type: integer
#        value: 1
#      - domain: 'NSGlobalDomain'
#        key: 'KeyRepeat'
#        type: integer
#        value: 2
#      - domain: 'com.apple.menuextra.clock'
#        key: 'DateFormat'
#        type: string
#        value: EEE MMM d  HH:mm
#      - domain: 'com.apple.finder'
#        key: 'FXPreferredViewStyle'
#        type: string
#        value: "clmv"
#      - domain: 'NSGlobalDomain'
#        key: 'NSNavPanelExpandedStateForSaveMode'
#        type: boolean
#        value: true
#      - domain: 'NSGlobalDomain'
#        key: 'PMPrintingExpandedStateForPrint'
#        type: boolean
#        value: true
#      - domain: 'com.apple.dock'
#        key: 'tilesize'
#        type: float
#        value: 32
