---

- hosts: 127.0.0.1
  connection: local

  vars:
    - superlimic_config_repo: https://github.com/joffotron/superlumic-config.git
    - user_name: joff
    - computername: cernan
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: joff@joff.codes
    - github_user_name: joffotron
    - git_user_name: Joseph Miller
    - git_user_email: "{{ user_email }}"
    - git_signing_key: 198C913B
    - apple_id_email: joff@googlehax.com
    # Override source dir
    - src_dir: "{{ home_dir }}/src/CareMonkey"
    - settings_export_dir: "{{ home_dir }}/tmp/SettingsExports"

    # Set these in secrets file:
    # github_auth_token
    # apple_id_password

  vars_files:
    - vars/osx_defaults.yml
    - vars/sublime_text_3.yml
    - vars/{{ user_name }}-secrets.yml

  roles:
    - { role: profile-all, tags: base }
    - { role: profile-developer, tags: base-dev }
    - { role: roderik.superlumic-sublimetext, tags: sublime }
    - { role: ruby, tags: ruby }
    - { role: python, tags: python }
    - { role: profile-caremonkey-dev, tags: caremonkey }
#    - other-languages

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - istat-menus
        - dropbox
        - xee
        - bartender
        - chicken
        - alfred
        - bettertouchtool
        - tresorit
        - evernote
        - skitch
        - gitkraken
        - monodraw
        - flux
        - datagrip
        - intellij-idea
        - rubymine
        - sonos
        - spotify
        - libreoffice

    - name: Local bin dir
      file: path="{{ home_dir }}/bin" state=directory

    - name: Powerline Shell Prompt
      git: repo=https://github.com/milkbikis/powerline-shell
           dest="{{ home_dir }}/bin/powerline-shell"
           version="master"

    - name: Run install for powerline shell prompt
      command: "python install.py"
      args:
        chdir: "{{ home_dir }}/bin/powerline-shell/"

    - name: homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/fuse
        - Caskroom/cask

    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - mas
        - certbot
        - z
        - ipcalc
        - jq
        - moreutils
#        - osxfuse
#        - ntfs-3g
        - packer
        - pidof
        - s3cmd

    - name: Signin to the Mac App Store
      command: mas signin {{ apple_id_email }} "{{ apple_id_password }}"

    - name: Install Mac App Store applications
      command: mas install {{ item.id }}
      with_items:
        - { 587512244 Kaleidoscope }
        - { 427515976 3Hub }
        - { 419330170 Moom }
        - { 410628904 Wunderlist }
        - { 824183456 Affinity Photo }
        - { 824171161 Affinity Designer }
        - { 557168941 Tweetbot }


    - name: Install Python pip packages
      pip: state=present name="{{ item }}"
      with_items:
        - awslogs
        - wharfee

    - name: create .ssh directory
      file:
        path: "{{ home_dir }}/.ssh/"
        state: directory
        mode: 0700

    - name: personal ssh config
      copy:
        src: files/ssh_config
        dest: "{{ home_dir }}/.ssh/ssh_config"

    - name: Create SettingsExports dir
      file: path={{ settings_export_dir }} state=directory

    - name: Copy Jetbrains Settings Files
      copy: src="{{ user_name }}/{{ item }}" dest="{{ settings_export_dir }}/{{ item }}"
      with_items:
        - RubyMine-settings.jar
        - IntelliJ-settings.jar
        - DataGrip-settings.jar
        - iStatMenusSettings.ismp
        - BetterTouchTool.settings
        - com.manytricks.Moom.plist  #for safekeeping

    - name: Kill Moom
      command: kill `pidof Moom`

    - name: killall cfprefsd so we can copy the Moom prefs
      command: killall cfprefsd

    - name: Copy moom config
      copy: src=joff/com.manytricks.Moom.plist dest="{{ home_dir }}/Library/Preferences/com.manytricks.Moom.plist"

    - name: Start Moom again
      command: open /Applications/Moom.app

    - name: OSX Keyboard shortcuts
      tags: osxshortcuts
      command: defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys {{ item.keyid }} "{enabled = {{ item.enabled }} ; value = { parameters = ({{ item.params }}); type = ‘standard’; }; }"
      with_items:
        - { keyid: 0, enabled: 1, params: '65535, 6, 4' }
        - { keyid: 1, enabled: 1, params: '65535, 7, 4' }
        - { keyid: 8, enabled: 0, params: '65535, 8, 4' }
        - { keyid: 9, enabled: 0, params: '65535, 9, 4' }
        - { keyid: 2, enabled: 1, params: '65535, 2, 4' }
        - { keyid: 0, enabled: 0, params: '65535, 0, 4' }
        - { keyid: 1, enabled: 0, params: '65535, 1, 4' }
        - { keyid: 2, enabled: 0, params: '65535, 3, 4' }
        - { keyid: 3, enabled: 1, params: '65535, 8, 4' }
        - { keyid: 5, enabled: 1, params: '56, 8, 4' }
        - { keyid: 0, enabled: 0, params: '65535, 5, 0' }
        - { keyid: 2, enabled: 1, params: '65535, 6, 4' }
        - { keyid: 3, enabled: 0, params: '65535, 5, 0' }
        - { keyid: 7, enabled: 1, params: '61, 4, 4' }
        - { keyid: 5, enabled: 1, params: '65535, 5, 0' }
        - { keyid: 9, enabled: 1, params: '65535, 5, 0' }
        - { keyid: 9, enabled: 1, params: '45, 7, 4' }
        - { keyid: 1, enabled: 0, params: '56, 8, 8' }
        - { keyid: 3, enabled: 1, params: '92, 2, 4' }
        - { keyid: 5, enabled: 0, params: '46, 7, 8' }
        - { keyid: 6, enabled: 0, params: '44, 3, 8' }
        - { keyid: 7, enabled: 1, params: '96, 0, 6' }
        - { keyid: 8, enabled: 1, params: '51, 0, 8' }
        - { keyid: 9, enabled: 1, params: '51, 0, 2' }
        - { keyid: 0, enabled: 1, params: '52, 1, 8' }
        - { keyid: 1, enabled: 1, params: '52, 1, 2' }
        - { keyid: 2, enabled: 0, params: '65535, 1, 0' }
        - { keyid: 3, enabled: 0, params: '65535, 5, 4' }
        - { keyid: 4, enabled: 0, params: '65535, 1, 2' }
        - { keyid: 5, enabled: 0, params: '65535, 5, 6' }
        - { keyid: 6, enabled: 1, params: '65535, 3, 0' }
        - { keyid: 7, enabled: 1, params: '65535, 3, 2' }
        - { keyid: 1, enabled: 1, params: '39, 0, 4' }
        - { keyid: 2, enabled: 0, params: '100, 2, 4' }
        - { keyid: 3, enabled: 1, params: '65535, 7, 0' }
        - { keyid: 4, enabled: 1, params: '65535, 3, 0' }
        - { keyid: 5, enabled: 1, params: '65535, 7, 8' }
        - { keyid: 6, enabled: 1, params: '65535, 3, 8' }
        - { keyid: 7, enabled: 1, params: '65535, 0, 4' }
        - { keyid: 9, enabled: 1, params: '65535, 6, 6' }
        - { keyid: 0, enabled: 1, params: '32, 9, 6' }
        - { keyid: 1, enabled: 1, params: '32, 9, 4' }
        - { keyid: 2, enabled: 0, params: '65535, 1, 0' }
        - { keyid: 3, enabled: 0, params: '65535, 1, 2' }
        - { keyid: 4, enabled: 0, params: '65535, 9, 6' }
        - { keyid: 5, enabled: 0, params: '65535, 9, 4' }
        - { keyid: 7, enabled: 1, params: '65535, 0, 4' }
        - { keyid: 9, enabled: 1, params: '65535, 3, 4' }
        - { keyid: 8, enabled: 1, params: '65535, 9, 4' }
        - { keyid: 0, enabled: 1, params: '65535, 3, 6' }
        - { keyid: 1, enabled: 1, params: '65535, 4, 4' }
        - { keyid: 2, enabled: 1, params: '65535, 4, 6' }
        - { keyid: 9, enabled: 1, params: '65535, 8, 4' }
        - { keyid: 8, enabled: 1, params: '47, 4, 8' }



