---

- name: Check for FileVault Full Disk Encryption
  command: fdesetup status
  become: yes
  register: fde_status

- name: Abort if Disk not encrypted
  fail: msg="Sorry, Please turn on FileVault Full Disk Encryption before proceeding"
  when: fde_status.stdout.find("FileVault is On.") != -1

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-drive
    - google-chrome
    - vlc
    - dash
    - iterm2
    - lastpass
    - slack

- name: install general brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - bash-completion
    - lastpass-cli
    - the_silver_searcher
    - ack
    - gnu-tar
    - git
    - git-extras

- name: Generate SSH keypair
  user: name={{ user_name }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
