---
- name: "[Raisebook] Make src directory"
  file: path="{{ raisebook_src }}/" state=directory

- name: "[Raisebook] Checkout repositories"
  git: repo="ssh://git@github.com/{{ item.account }}/{{ item.repo }}.git"
       dest="{{ raisebook_src }}/{{ item.repo }}"
       update=no
  with_items:
    - { account: 'raisebook', repo: 'raisebook' }
    - { account: 'raisebook', repo: 'backend' }
    - { account: 'raisebook', repo: 'frontend' }
    - { account: 'raisebook', repo: 'proxy' }

- name: "[Raisebook] Add bin to path"
  lineinfile: dest={{ home_dir }}/.bash_profile
              line="export PATH=$PATH:{{ raisebook_src }}/raisebook/bin"

- name: "[Raisebook] Check for subtree remotes"
  command: git remote -v | grep {{ item }}
           chdir="{{ raisebook_src }}/raisebook"
  register: found_remote_{{ item }}
  with_items:
    - backend
    - frontend
    - proxy

- name: "[Raisebook] Add subtree remote {{ item.name }}"
  command: git remote add {{ item.name }} {{ item.remote }}
           chdir="{{ raisebook_src }}/raisebook"
  when: found_remote_{{ item }}
  with_items:
    - { name: 'backend',  remote: 'git@github.com:raisebook/backend.git' }
    - { name: 'frontend', remote: 'git@github.com:raisebook/frontend.git' }
    - { name: 'proxy',    remote: 'git@github.com:raisebook/proxy.git' }

