---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap homebrew/dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - htop
    - watch
    - rsync

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - dash
    - iterm2

- name: Copy dotfiles
  copy: src=files/{{ user_name }}/{{ item }} dest={{ home_dir }}/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - npmrc
    - vimrc

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

