---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap homebrew/dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - htop
    - watch
    - rsync


- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

