---
- name: link vimrc-after
  file: path="{{ home_dir }}/.vimrc.after" src="frank/files/vimrc.after"
- name: link vimrc-before
  file: path="{{ home_dir }}/.vimrc.before" src="frank/files/vimrc.before"

- name: install gruvbox colorscheme
  git: repo="https://github.com/morhetz/gruvbox.git" "dest={{ home_dir }}/.janus/gruvbox"

- name: install editorconfig-vim
  git: repo="https://github.com/editorconfig/editorconfig-vim.git" "dest={{ home_dir }}/.janus/editorconfig-vim"

