---
- name: "[Ruby] install ruby brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - rbenv
    - rbenv-binstubs
    - rbenv-default-gems
    - ruby-build

- name: "[Ruby] Get rbenv root"
  command: rbenv root
  register: rbenv_root

- name: "[Ruby] Set default gems for rbenv"
  copy: src=files/rbenv-default-gems dest="{{ rbenv_root.stdout }}"/default-gems

- name: "[Ruby] install ruby versions"
  command: rbenv install -s {{ item }}
  with_items:
    - 2.3.1
