---
- name: install ruby brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - rbenv
    - rbenv-binstubs
    - ruby-build

- name: install ruby versions
  command: rbenv install -s {{ item }}
  with_items:
    - 2.3.0

#- name: Install update-rubygems gem
#  gem: name=rubygems-update state=present
#
#- name: Upgrade rubygems
#  become: yes
#  command: "{{ item }}"
#  with_items:
#    - "upgrade_rubygems"
#    - "gem update --system"
